# Generated by Django 5.0.2 on 2024-02-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("image", "Зображення"),
                            ("document", "Документи"),
                            ("video", "Відео"),
                            ("other", "Інше"),
                        ],
                        max_length=20,
                    ),
                ),
                ("user_id", models.IntegerField()),
            ],
        ),
    ]
