# Generated by Django 5.0.2 on 2024-02-21 11:51

import django.db.models.deletion
import filemanager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filemanager", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="user_id",
        ),
        migrations.AddField(
            model_name="file",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="file",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(),
        ),
    ]
