# Generated by Django 5.0.2 on 2024-02-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filemanager", "0002_remove_file_user_id_file_url_file_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
