# Generated by Django 5.0.2 on 2024-02-24 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filemanager", "0003_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="filemanager.category",
            ),
        ),
    ]
